name: CMake

on:
  push:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  arm64_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: CMake build and run
      run: |
        docker run --platform linux/arm64/v8 --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp arm64v8/gcc bash -c "apt update && apt install -y cmake; mkdir build && cmake -B build && cmake --build build --config ${{env.BUILD_TYPE}} && cmake --install build; ./dist/BarcodeReader ./images/AllSupportedBarcodeTypes.png ./license-key.txt"
        
    - name: Archive Release
      uses: darshitsri/zip-release@v1
      with:
        type: 'zip'
        filename: arm64.zip
        exclusions: '*.git* /*node_modules/* .editorconfig'
        path: ${{github.workspace}}/dist

    - uses: actions/upload-artifact@v2
      with:
        path: ./*.zip
