name: CMake

on:
  push:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  arm64_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: CMake build and run
      uses: darshitsri/composite-action@v7
      with:
         PATH : /home/runner/work/c-program-code/c-program-code
  #       DIST_FOLDER : dist/BarcodeReader
  #       IMAGE : images/AllSupportedBarcodeTypes.png
  #       LICENSE: license-key.txt
    - name: Run manuall    
      run: |
        pwd
        ls -lrths
        bash -c "mkdir build && cmake -B build && cmake --build build --config ${{env.BUILD_TYPE}} && cmake --install build; ./dist/BarcodeReader ./images/AllSupportedBarcodeTypes.png ./license-key.txt"
    - name: Archive Release
      uses: darshitsri/zip-release@v3
      with:
        type: 'zip'
        filename: arm64.zip
        exclusions: '*.git* /*node_modules/* .editorconfig'
        path: ${{github.workspace}}/dist

    - uses: actions/upload-artifact@v2
      with:
        path: ./*.zip
