name: for testing purpose

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
 #   - name: Checkout submodules
 #     run: git submodule update --init --recursive
      with:
       submodules: recursive
       token: ${{ secrets.PAT_TOKEN }}
    - name: to test the directory
      run: cd .build/project1 &&
           ls -lrths &&
           pwd
